// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteAppByIdData, DeleteAppByIdErrors, DeleteAppByIdResponses, DeleteTokenByIdData, DeleteTokenByIdErrors, DeleteTokenByIdResponses, GetAppByIdData, GetAppByIdErrors, GetAppByIdResponses, GetAppData, GetAppErrors, GetAppResponses, GetProfileData, GetProfileErrors, GetProfileResponses, GetTokenByIdData, GetTokenByIdErrors, GetTokenByIdResponses, GetTokenData, GetTokenErrors, GetTokenResponses, PostAppData, PostAppErrors, PostAppResponses, PostTokenData, PostTokenErrors, PostTokenResponses, PutProfileData, PutProfileErrors, PutProfileResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new DevAgentSdk()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class DevAgentSdk extends HeyApiClient {
    public static readonly __registry = new HeyApiRegistry<DevAgentSdk>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        DevAgentSdk.__registry.set(this, args?.key);
    }
    
    /**
     * Get profile
     *
     * Get the current user's profile.
     */
    public getProfile<ThrowOnError extends boolean = false>(options?: Options<GetProfileData, ThrowOnError>) {
        return (options?.client ?? this.client).get<GetProfileResponses, GetProfileErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/profile',
            ...options
        });
    }
    
    /**
     * Update profile
     *
     * Update the current user's profile.
     */
    public putProfile<ThrowOnError extends boolean = false>(options: Options<PutProfileData, ThrowOnError>) {
        return (options.client ?? this.client).put<PutProfileResponses, PutProfileErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/profile',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * List apps
     *
     * List the current user's registered apps.
     */
    public getApp<ThrowOnError extends boolean = false>(options?: Options<GetAppData, ThrowOnError>) {
        return (options?.client ?? this.client).get<GetAppResponses, GetAppErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/app',
            ...options
        });
    }
    
    /**
     * Create app
     *
     * Create an app.
     */
    public postApp<ThrowOnError extends boolean = false>(options: Options<PostAppData, ThrowOnError>) {
        return (options.client ?? this.client).post<PostAppResponses, PostAppErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/app',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete app
     *
     * Delete the app with the given ID.
     */
    public deleteAppById<ThrowOnError extends boolean = false>(options: Options<DeleteAppByIdData, ThrowOnError>) {
        return (options.client ?? this.client).delete<DeleteAppByIdResponses, DeleteAppByIdErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/app/{id}',
            ...options
        });
    }
    
    /**
     * Get app
     *
     * Get the app with the given ID.
     */
    public getAppById<ThrowOnError extends boolean = false>(options: Options<GetAppByIdData, ThrowOnError>) {
        return (options.client ?? this.client).get<GetAppByIdResponses, GetAppByIdErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/app/{id}',
            ...options
        });
    }
    
    /**
     * List tokens
     *
     * List the current user's personal access tokens.
     */
    public getToken<ThrowOnError extends boolean = false>(options?: Options<GetTokenData, ThrowOnError>) {
        return (options?.client ?? this.client).get<GetTokenResponses, GetTokenErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/token',
            ...options
        });
    }
    
    /**
     * Create token
     *
     * Create a personal access token.
     */
    public postToken<ThrowOnError extends boolean = false>(options?: Options<PostTokenData, ThrowOnError>) {
        return (options?.client ?? this.client).post<PostTokenResponses, PostTokenErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/token',
            ...options
        });
    }
    
    /**
     * Delete token
     *
     * Delete the personal access token with the given ID.
     */
    public deleteTokenById<ThrowOnError extends boolean = false>(options: Options<DeleteTokenByIdData, ThrowOnError>) {
        return (options.client ?? this.client).delete<DeleteTokenByIdResponses, DeleteTokenByIdErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/token/{id}',
            ...options
        });
    }
    
    /**
     * Get token
     *
     * Get the personal access token with the given ID.
     */
    public getTokenById<ThrowOnError extends boolean = false>(options: Options<GetTokenByIdData, ThrowOnError>) {
        return (options.client ?? this.client).get<GetTokenByIdResponses, GetTokenByIdErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/token/{id}',
            ...options
        });
    }
}
