// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | 'http://localhost:3000' | (string & {});
};

/**
 * A user.
 */
export type User = {
    /**
     * Unique object identifier.
     * The format and length of IDs may change over time.
     */
    id: string;
    /**
     * Name of the user.
     */
    name: string | null;
    /**
     * Email address of the user.
     */
    email: string | null;
    /**
     * GitHub username of the user.
     */
    username: string | null;
    /**
     * Avatar URL of the user.
     */
    avatarUrl: string | null;
};

/**
 * Updated user profile information.
 */
export type Profile = {
    user: User;
};

/**
 * Permission error
 */
export type ErrorResponse = {
    /**
     * The error type category
     */
    type: 'validation' | 'authentication' | 'forbidden' | 'not_found' | 'rate_limit' | 'internal';
    /**
     * Machine-readable error code identifier
     */
    code: string;
    /**
     * Human-readable error message
     */
    message: string;
    /**
     * The parameter that caused the error (if applicable)
     */
    param?: string;
    /**
     * Additional error context information
     */
    details?: unknown;
};

/**
 * App.
 */
export type App = {
    /**
     * Unique object identifier.
     * The format and length of IDs may change over time.
     */
    id: string;
    /**
     * Name of the app.
     */
    name: string;
    /**
     * Redirect URI of the app.
     */
    redirectURI: string;
    /**
     * OAuth 2.0 client secret of the app (obfuscated).
     */
    secret: string;
};

/**
 * Personal access token.
 */
export type Token = {
    /**
     * Unique object identifier.
     * The format and length of IDs may change over time.
     */
    id: string;
    /**
     * The created time for the token.
     */
    created: string;
    /**
     * Personal access token (obfuscated).
     */
    token: string;
};

export type GetProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/profile';
};

export type GetProfileErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Too Many Requests
     */
    429: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetProfileError = GetProfileErrors[keyof GetProfileErrors];

export type GetProfileResponses = {
    /**
     * User profile information.
     */
    200: Profile;
};

export type GetProfileResponse = GetProfileResponses[keyof GetProfileResponses];

export type PutProfileData = {
    /**
     * The user's updated profile information.
     */
    body: {
        name: string;
        email: string;
    };
    path?: never;
    query?: never;
    url: '/profile';
};

export type PutProfileErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Too Many Requests
     */
    429: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type PutProfileError = PutProfileErrors[keyof PutProfileErrors];

export type PutProfileResponses = {
    /**
     * Updated user profile information.
     */
    200: Profile;
};

export type PutProfileResponse = PutProfileResponses[keyof PutProfileResponses];

export type GetAppData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/app';
};

export type GetAppErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Too Many Requests
     */
    429: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetAppError = GetAppErrors[keyof GetAppErrors];

export type GetAppResponses = {
    /**
     * List of apps.
     */
    200: Array<App>;
};

export type GetAppResponse = GetAppResponses[keyof GetAppResponses];

export type PostAppData = {
    /**
     * Basic app information.
     */
    body: {
        name: string;
        redirectURI: string;
    };
    path?: never;
    query?: never;
    url: '/app';
};

export type PostAppErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Too Many Requests
     */
    429: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type PostAppError = PostAppErrors[keyof PostAppErrors];

export type PostAppResponses = {
    /**
     * OAuth 2.0 client ID and secret.
     */
    200: {
        /**
         * OAuth 2.0 client ID.
         */
        id: string;
        /**
         * OAuth 2.0 client secret.
         */
        secret: string;
    };
};

export type PostAppResponse = PostAppResponses[keyof PostAppResponses];

export type DeleteAppByIdData = {
    body?: never;
    path: {
        /**
         * ID of the app to delete.
         */
        id: string;
    };
    query?: never;
    url: '/app/{id}';
};

export type DeleteAppByIdErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Too Many Requests
     */
    429: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type DeleteAppByIdError = DeleteAppByIdErrors[keyof DeleteAppByIdErrors];

export type DeleteAppByIdResponses = {
    /**
     * App was deleted successfully.
     */
    200: 'ok';
};

export type DeleteAppByIdResponse = DeleteAppByIdResponses[keyof DeleteAppByIdResponses];

export type GetAppByIdData = {
    body?: never;
    path: {
        /**
         * ID of the app to get.
         */
        id: string;
    };
    query?: never;
    url: '/app/{id}';
};

export type GetAppByIdErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Too Many Requests
     */
    429: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetAppByIdError = GetAppByIdErrors[keyof GetAppByIdErrors];

export type GetAppByIdResponses = {
    /**
     * App.
     */
    200: App;
};

export type GetAppByIdResponse = GetAppByIdResponses[keyof GetAppByIdResponses];

export type GetTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/token';
};

export type GetTokenErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Too Many Requests
     */
    429: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetTokenError = GetTokenErrors[keyof GetTokenErrors];

export type GetTokenResponses = {
    /**
     * List of personal access tokens.
     */
    200: Array<Token>;
};

export type GetTokenResponse = GetTokenResponses[keyof GetTokenResponses];

export type PostTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/token';
};

export type PostTokenErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Too Many Requests
     */
    429: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type PostTokenError = PostTokenErrors[keyof PostTokenErrors];

export type PostTokenResponses = {
    /**
     * Personal access token ID and value.
     */
    200: {
        /**
         * Personal token ID.
         */
        id: string;
        /**
         * Personal access token. Include this in the Authorization header (`Bearer <token>`) when accessing the API.
         */
        token: string;
    };
};

export type PostTokenResponse = PostTokenResponses[keyof PostTokenResponses];

export type DeleteTokenByIdData = {
    body?: never;
    path: {
        /**
         * ID of the personal token to delete.
         */
        id: string;
    };
    query?: never;
    url: '/token/{id}';
};

export type DeleteTokenByIdErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Too Many Requests
     */
    429: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type DeleteTokenByIdError = DeleteTokenByIdErrors[keyof DeleteTokenByIdErrors];

export type DeleteTokenByIdResponses = {
    /**
     * Personal access token was deleted successfully.
     */
    200: 'ok';
};

export type DeleteTokenByIdResponse = DeleteTokenByIdResponses[keyof DeleteTokenByIdResponses];

export type GetTokenByIdData = {
    body?: never;
    path: {
        /**
         * ID of the personal token to get.
         */
        id: string;
    };
    query?: never;
    url: '/token/{id}';
};

export type GetTokenByIdErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Too Many Requests
     */
    429: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetTokenByIdError = GetTokenByIdErrors[keyof GetTokenByIdErrors];

export type GetTokenByIdResponses = {
    /**
     * Personal access token.
     */
    200: Token;
};

export type GetTokenByIdResponse = GetTokenByIdResponses[keyof GetTokenByIdResponses];
