// Auto-generated by build.ts — do not edit manually
import cmd0 from "./app";
import cmd1 from "./login";
import cmd2 from "./logout";
import cmd3 from "./profile";
import cmd4 from "./token";

export const commands = [cmd0, cmd1, cmd2, cmd3, cmd4];
