/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

import "sst"
declare module "sst" {
  export interface Resource {
    "AntropicApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Database": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.sst.Linkable"
      "url": string
      "username": string
    }
    "GitHubAppId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GitHubAppPrivateKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GitHubClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GitHubClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GitHubWebhookSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ResendApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SenderEmailDomain": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "sst" {
  export interface Resource {
    "Api": cloudflare.Service
    "Artifacts": cloudflare.R2Bucket
    "AuthKv": cloudflare.KVNamespace
    "AuthWorker": cloudflare.Service
    "Bus": cloudflare.Queue
    "Console": cloudflare.Service
  }
}

import "sst"
export {}