import { app } from "../../src/api/routes";

type OpenAPISchema = {
  type?: string;
  properties?: Record<string, OpenAPISchema>;
  required?: string[];
  allOf?: OpenAPISchema[];
  oneOf?: OpenAPISchema[];
  anyOf?: OpenAPISchema[];
  items?: OpenAPISchema;
  $ref?: string;
  enum?: any[];
  const?: any;
  format?: string;
  pattern?: string;
  minLength?: number;
  maxLength?: number;
  minimum?: number;
  maximum?: number;
  minItems?: number;
  maxItems?: number;
  nullable?: boolean;
  additionalProperties?: boolean | OpenAPISchema;
  example?: any;
  [key: string]: any;
};

type OpenAPIDocument = {
  components?: { schemas?: Record<string, OpenAPISchema> };
  paths?: Record<string, Record<string, any>>;
};

/**
 * Validates API responses against the OpenAPI spec generated by the Hono app.
 * Single source of truth: the `/openapi.json` route.
 */
export class SchemaValidator {
  private static spec: OpenAPIDocument | null = null;
  private static specPromise: Promise<void> | null = null;

  // ── Spec access ──────────────────────────────────────────────

  private static async getSpec(): Promise<OpenAPIDocument> {
    if (this.spec) return this.spec;
    if (!this.specPromise) {
      this.specPromise = (async () => {
        const res = await app.request("/openapi.json");
        if (!res.ok) throw new Error(`Failed to fetch OpenAPI spec: ${res.status}`);
        this.spec = (await res.json()) as OpenAPIDocument;
      })();
    }
    await this.specPromise;
    return this.spec!;
  }

  // ── Path matching ────────────────────────────────────────────

  /**
   * Match a concrete request path (e.g. `/token/abc`) to an OpenAPI
   * path template (e.g. `/token/{id}`).
   */
  private static findOpenAPIPath(spec: OpenAPIDocument, path: string): string | undefined {
    const paths = spec.paths;
    if (!paths) return undefined;

    const normalized = path.startsWith("/") ? path : `/${path}`;
    if (paths[normalized]) return normalized;

    const parts = normalized.split("/").filter(Boolean);
    for (const candidate of Object.keys(paths)) {
      const candidateParts = candidate.split("/").filter(Boolean);
      if (parts.length !== candidateParts.length) continue;
      const match = candidateParts.every(
        (seg, i) => (seg.startsWith("{") && seg.endsWith("}")) || seg === parts[i],
      );
      if (match) return candidate;
    }
    return undefined;
  }

  // ── $ref resolution ──────────────────────────────────────────

  private static resolve(
    schema: OpenAPISchema,
    spec: OpenAPIDocument,
    seen: Set<string> = new Set(),
  ): OpenAPISchema {
    if (!schema) return schema;

    if (schema.$ref) {
      if (seen.has(schema.$ref)) return { type: "object" }; // circular
      seen = new Set(seen).add(schema.$ref);
      const name = schema.$ref.split("/").pop()!;
      const ref = spec.components?.schemas?.[name];
      if (!ref) throw new Error(`Unresolved $ref: ${schema.$ref}`);
      return this.resolve(structuredClone(ref), spec, seen);
    }

    if (schema.properties) {
      const props: Record<string, OpenAPISchema> = {};
      for (const [k, v] of Object.entries(schema.properties))
        props[k] = this.resolve(v, spec, seen);
      schema = { ...schema, properties: props };
    }
    if (schema.items) schema = { ...schema, items: this.resolve(schema.items, spec, seen) };
    for (const key of ["allOf", "oneOf", "anyOf"] as const) {
      if (schema[key])
        schema = {
          ...schema,
          [key]: schema[key]!.map((s) => this.resolve(s, spec, seen)),
        };
    }
    return schema;
  }

  // ── Validation ───────────────────────────────────────────────

  private static validate(data: any, schema: OpenAPISchema, errors: string[], path = "$"): boolean {
    if (!schema) return true;

    // nullable
    if (schema.nullable && data === null) return true;

    // composition
    if (schema.allOf) {
      return schema.allOf.every((s, i) => this.validate(data, s, errors, `${path}.allOf[${i}]`));
    }
    if (schema.oneOf) {
      const ok = schema.oneOf.some((s) => {
        const e: string[] = [];
        return this.validate(data, s, e, path);
      });
      if (!ok) errors.push(`${path}: matched none of oneOf`);
      return ok;
    }
    if (schema.anyOf) {
      const ok = schema.anyOf.some((s) => {
        const e: string[] = [];
        return this.validate(data, s, e, path);
      });
      if (!ok) errors.push(`${path}: matched none of anyOf`);
      return ok;
    }

    // infer type from shape
    const type = schema.type ?? (schema.properties ? "object" : undefined);
    if (!type) return true; // unconstrained

    // enum / const
    if (schema.enum && !schema.enum.includes(data)) {
      errors.push(`${path}: ${JSON.stringify(data)} not in enum`);
      return false;
    }
    if (schema.const !== undefined && data !== schema.const) {
      errors.push(`${path}: expected const ${JSON.stringify(schema.const)}`);
      return false;
    }

    switch (type) {
      case "object": {
        if (typeof data !== "object" || data === null || Array.isArray(data)) {
          errors.push(`${path}: expected object, got ${typeof data}`);
          return false;
        }
        let ok = true;
        if (schema.required) {
          for (const key of schema.required) {
            if (!(key in data)) {
              errors.push(`${path}: missing required property "${key}"`);
              ok = false;
            }
          }
        }
        if (schema.properties) {
          for (const [key, sub] of Object.entries(schema.properties)) {
            if (key in data) {
              if (!this.validate(data[key], sub, errors, `${path}.${key}`)) ok = false;
            }
          }
        }
        return ok;
      }

      case "array": {
        if (!Array.isArray(data)) {
          errors.push(`${path}: expected array, got ${typeof data}`);
          return false;
        }
        let ok = true;
        if (schema.minItems != null && data.length < schema.minItems) {
          errors.push(`${path}: array too short (${data.length} < ${schema.minItems})`);
          ok = false;
        }
        if (schema.maxItems != null && data.length > schema.maxItems) {
          errors.push(`${path}: array too long (${data.length} > ${schema.maxItems})`);
          ok = false;
        }
        if (schema.items) {
          data.forEach((item, i) => {
            if (!this.validate(item, schema.items!, errors, `${path}[${i}]`)) ok = false;
          });
        }
        return ok;
      }

      case "string":
        if (typeof data !== "string") {
          errors.push(`${path}: expected string, got ${typeof data}`);
          return false;
        }
        if (schema.pattern && !new RegExp(schema.pattern).test(data)) {
          errors.push(`${path}: string does not match pattern ${schema.pattern}`);
          return false;
        }
        if (schema.minLength != null && data.length < schema.minLength) {
          errors.push(`${path}: string too short`);
          return false;
        }
        if (schema.maxLength != null && data.length > schema.maxLength) {
          errors.push(`${path}: string too long`);
          return false;
        }
        return true;

      case "number":
      case "integer":
        if (typeof data !== "number") {
          errors.push(`${path}: expected ${type}, got ${typeof data}`);
          return false;
        }
        if (type === "integer" && !Number.isInteger(data)) {
          errors.push(`${path}: expected integer`);
          return false;
        }
        if (schema.minimum != null && data < schema.minimum) {
          errors.push(`${path}: ${data} < minimum ${schema.minimum}`);
          return false;
        }
        if (schema.maximum != null && data > schema.maximum) {
          errors.push(`${path}: ${data} > maximum ${schema.maximum}`);
          return false;
        }
        return true;

      case "boolean":
        if (typeof data !== "boolean") {
          errors.push(`${path}: expected boolean, got ${typeof data}`);
          return false;
        }
        return true;

      case "null":
        if (data !== null) {
          errors.push(`${path}: expected null`);
          return false;
        }
        return true;

      default:
        return true;
    }
  }

  // ── Sample data generation ───────────────────────────────────

  private static sample(schema: OpenAPISchema): any {
    if (!schema) return null;
    if (schema.example !== undefined) return schema.example;

    if (schema.allOf) {
      return schema.allOf.reduce((acc, s) => Object.assign(acc, this.sample(s)), {});
    }
    if (schema.oneOf?.[0]) return this.sample(schema.oneOf[0]);
    if (schema.anyOf?.[0]) return this.sample(schema.anyOf[0]);

    const type = schema.type ?? (schema.properties ? "object" : undefined);
    if (schema.enum?.length) return schema.enum[0];
    if (schema.const !== undefined) return schema.const;

    switch (type) {
      case "object": {
        const out: Record<string, any> = {};
        if (schema.properties)
          for (const [k, v] of Object.entries(schema.properties)) out[k] = this.sample(v);
        return out;
      }
      case "array":
        return schema.items ? [this.sample(schema.items)] : [];
      case "string":
        return schema.format === "email"
          ? "user@example.com"
          : schema.format === "date-time"
            ? new Date().toISOString()
            : schema.format === "uuid"
              ? "00000000-0000-0000-0000-000000000000"
              : schema.format === "uri"
                ? "https://example.com"
                : "sample";
      case "number":
        return schema.minimum ?? 1.0;
      case "integer":
        return schema.minimum ?? 1;
      case "boolean":
        return true;
      case "null":
        return null;
      default:
        return null;
    }
  }

  // ── Public API ───────────────────────────────────────────────

  /**
   * Return the status codes declared by the given route in the OpenAPI spec.
   */
  static async getRouteResponseStatusCodes(path: string, method = "get"): Promise<number[]> {
    const spec = await this.getSpec();
    const apiPath = this.findOpenAPIPath(spec, path.startsWith("/") ? path : `/${path}`);
    if (!apiPath) return [];
    const responses = spec.paths?.[apiPath]?.[method.toLowerCase()]?.responses;
    return responses ? Object.keys(responses).map(Number) : [];
  }

  /**
   * Validate a live response against the schema declared in the OpenAPI spec.
   * Returns the parsed JSON body or throws on validation failure.
   */
  static async validateResponse(response: Response, path: string, method = "get"): Promise<any> {
    const spec = await this.getSpec();
    const data = await response.clone().json();
    const normalized = path.startsWith("/") ? path : `/${path}`;
    const apiPath = this.findOpenAPIPath(spec, normalized);

    if (!apiPath) {
      // No matching path in spec — can't validate, just return data
      console.warn(`No OpenAPI path found for ${method.toUpperCase()} ${path}`);
      return data;
    }

    const operation = spec.paths?.[apiPath]?.[method.toLowerCase()];
    const responseSpec =
      operation?.responses?.[response.status]?.content?.["application/json"]?.schema;

    if (!responseSpec) {
      console.warn(`No response schema for ${method.toUpperCase()} ${path} [${response.status}]`);
      return data;
    }

    const resolved = this.resolve(responseSpec, spec);
    const errors: string[] = [];
    if (!this.validate(data, resolved, errors)) {
      throw new Error(
        `Response validation failed for ${method.toUpperCase()} ${path} [${response.status}]:\n  ${errors.join("\n  ")}`,
      );
    }

    return data;
  }

  /**
   * Create an invalid request body for a route by generating a valid sample
   * and then stripping a required field. Returns `null` if the route has no
   * request body schema or no required fields to strip.
   */
  static async createInvalidRequestBody(path: string, method = "post"): Promise<any> {
    const spec = await this.getSpec();
    const normalized = path.startsWith("/") ? path : `/${path}`;
    const apiPath = this.findOpenAPIPath(spec, normalized);
    if (!apiPath) return null;

    const operation = spec.paths?.[apiPath]?.[method.toLowerCase()];
    const bodySchema = operation?.requestBody?.content?.["application/json"]?.schema;
    if (!bodySchema) return null;

    const resolved = this.resolve(bodySchema, spec);
    if (resolved.type !== "object" || !resolved.required?.length || !resolved.properties)
      return null;

    const body = this.sample(resolved);
    const field = resolved.required[0]!;
    if (body && field in body) {
      delete body[field];
      return body;
    }

    return null;
  }
}
