import { appendFileSync } from "fs";
import * as core from "@actions/core";
import * as exec from "@actions/exec";
import {
  createApiClient,
  execWithOutput,
  getContext,
  readContextTags,
  readEventPayload,
  readOptionalTags,
  uniqueTags,
} from "@agents/actions-core";

async function run() {
  const prPrefix = core.getState("pr_prefix");
  const startMsStr = core.getState("start_ms");
  const startMs = startMsStr ? parseInt(startMsStr, 10) : Date.now();
  const branch = core.getState("branch");
  const runUrl = core.getState("run_url");
  const startEventId = core.getState("start_event_id");

  if (!branch) {
    core.warning("No branch state found — main step likely failed, skipping finish.");
    return;
  }

  if (!prPrefix) {
    core.setFailed("pr_prefix state is empty — cannot create PR.");
    return;
  }

  const token = process.env.GITHUB_TOKEN;
  if (!token) throw new Error("GITHUB_TOKEN not set");

  const repository = process.env.GITHUB_REPOSITORY ?? "";
  const { issue } = readEventPayload();
  const extraTags = readOptionalTags(core.getInput("tags"));

  // Re-configure git credentials (local scope to avoid polluting global git config)
  const encodedAuth = Buffer.from(`x-access-token:${token}`).toString("base64");
  await exec.exec("git", [
    "config",
    "--local",
    "http.https://github.com/.extraheader",
    `AUTHORIZATION: basic ${encodedAuth}`,
  ]);

  // Commit and push
  await exec.exec("git", ["add", "-A"]);
  const diffCode = await exec.exec("git", ["diff", "--staged", "--quiet"], {
    ignoreReturnCode: true,
  });
  if (diffCode === 0) {
    core.setFailed("No changes to commit — agent made no modifications.");
    return;
  }
  await exec.exec("git", ["commit", "-m", `feat: implement issue #${issue.number}`]);
  await exec.exec("git", ["push", "origin", branch]);

  // Resolve base branch (needed before diff)
  let baseBranch = core.getState("base_branch");
  if (!baseBranch) {
    try {
      baseBranch = await execWithOutput("gh", [
        "repo",
        "view",
        "--json",
        "defaultBranchRef",
        "-q",
        ".defaultBranchRef.name",
      ]);
    } catch (err) {
      core.warning(`Could not resolve default branch, falling back to "main": ${err}`);
      baseBranch = "main";
    }
  }

  // Collect diff metrics against base branch
  await exec.exec("git", ["fetch", "origin", baseBranch, "--depth=1"]);
  const diffStat = await execWithOutput("git", [
    "diff",
    `origin/${baseBranch}...HEAD`,
    "--numstat",
  ]);
  let linesAdded = 0;
  let linesRemoved = 0;
  for (const line of diffStat.split("\n").filter(Boolean)) {
    const [added, removed] = line.split("\t");
    linesAdded += parseInt(added!) || 0;
    linesRemoved += parseInt(removed!) || 0;
  }
  const durationMs = Date.now() - startMs;

  // Create PR
  const prTitle = prPrefix.charAt(0).toUpperCase() + prPrefix.slice(1);
  const prBody = `Closes #${issue.number}\n\n---\nGenerated by [${prPrefix}](${runUrl})`;
  let prUrl = "";
  try {
    prUrl = await execWithOutput("gh", [
      "pr",
      "create",
      "--title",
      `${prTitle}: ${issue.title}`,
      "--body",
      prBody,
      "--base",
      baseBranch,
      "--head",
      branch,
    ]);
  } catch (err) {
    // Check if a PR already exists for this branch (idempotent re-run)
    try {
      prUrl = await execWithOutput("gh", [
        "pr",
        "view",
        "--head",
        branch,
        "--json",
        "url",
        "-q",
        ".url",
      ]);
      core.info(`PR already exists: ${prUrl}`);
    } catch {
      core.setFailed(`PR creation failed: ${err}`);
      return;
    }
  }

  const prNumberMatch = prUrl.match(/\/pull\/(\d+)/);
  const pullRequestNumber = prNumberMatch ? parseInt(prNumberMatch[1]!) : undefined;

  // Append PR tag and diff metrics to context
  const contextTagsFile = process.env.AGENTS_CONTEXT_TAGS_FILE;
  if (contextTagsFile) {
    if (pullRequestNumber) appendFileSync(contextTagsFile, `gh:pr:${pullRequestNumber}\n`);
    appendFileSync(contextTagsFile, `metric:duration_ms:${durationMs}\n`);
    appendFileSync(contextTagsFile, `metric:lines_added:${linesAdded}\n`);
    appendFileSync(contextTagsFile, `metric:lines_removed:${linesRemoved}\n`);
  }

  // Emit agents.implement.completed with full inherited context
  const agentsToken = core.getInput("token");
  const apiUrl = core.getInput("url");
  if (agentsToken) {
    const sdk = createApiClient(agentsToken, apiUrl);
    try {
      const tags = uniqueTags([...readContextTags(), ...extraTags]);
      await sdk.postEvents({
        eventIngestInput: {
          repoFullName: repository,
          parentEventId: startEventId || null,
          origin: "action",
          type: "agents.implement.completed",
          tags,
          data: {
            branch,
            issueNumber: issue.number,
            pullRequestNumber: pullRequestNumber ?? null,
            linesAdded,
            linesRemoved,
            durationMs,
            prUrl,
            runUrl,
          },
        },
      });
    } catch (err) {
      core.warning(`Failed to post agents.implement.completed event: ${err}`);
    }
  }

  // Write job summary
  const ctx = getContext();
  const contextTags = readContextTags();
  const metricRows = contextTags
    .filter((t) => t.startsWith("metric:"))
    .map((t) => {
      const parts = t.split(":");
      return [parts[1] ?? "", parts.slice(2).join(":")] as [string, string];
    });

  await core.summary
    .addHeading(`${prTitle} Implementation`)
    .addTable([
      [
        { data: "Metric", header: true },
        { data: "Value", header: true },
      ],
      ["Prefix", `\`${prPrefix}\``],
      ["Branch", `\`${branch}\``],
      ["Lines added", linesAdded.toString()],
      ["Lines removed", linesRemoved.toString()],
      ["Duration", `${durationMs}ms`],
      ["PR", prUrl],
      ["Run", runUrl],
      ...metricRows,
    ])
    .write();
}

run().catch(core.setFailed);
