import * as core from "@actions/core";
import * as exec from "@actions/exec";
import {
  createApiClient,
  execWithOutput,
  metricTags,
  readCustomMetrics,
  readEventPayload,
  readOptionalTags,
  uniqueTags,
} from "./utils";

async function run() {
  const prPrefix = core.getState("pr_prefix");
  const startMsStr = core.getState("start_ms");
  const startMs = startMsStr ? parseInt(startMsStr, 10) : Date.now();
  const branch = core.getState("branch");
  const runUrl = core.getState("run_url");
  const startEventId = core.getState("start_event_id");

  if (!branch) {
    core.warning("No branch state found — main step likely failed, skipping post.");
    return;
  }

  if (!prPrefix) {
    core.setFailed("pr_prefix state is empty — cannot create PR.");
    return;
  }

  const token = process.env.GITHUB_TOKEN;
  if (!token) throw new Error("GITHUB_TOKEN not set");

  const repository = process.env.GITHUB_REPOSITORY ?? "";
  const { issue } = readEventPayload();
  const extraTags = readOptionalTags(core.getInput("tags"));

  // Re-configure git credentials — the agent may have modified git config,
  // and post hooks run in a context where checkout's credential helper
  // may no longer be active.
  await exec.exec(
    "git",
    ["config", "--local", "--unset-all", "http.https://github.com/.extraheader"],
    { ignoreReturnCode: true },
  );
  const encodedAuth = Buffer.from(`x-access-token:${token}`).toString("base64");
  await exec.exec("git", [
    "config",
    "--global",
    "http.https://github.com/.extraheader",
    `AUTHORIZATION: basic ${encodedAuth}`,
  ]);

  // Commit and push
  await exec.exec("git", ["add", "-A"]);
  const diffCode = await exec.exec("git", ["diff", "--staged", "--quiet"], {
    ignoreReturnCode: true,
  });
  if (diffCode === 0) {
    core.setFailed("No changes to commit — agent made no modifications.");
    return;
  }
  await exec.exec("git", ["commit", "-m", `feat: implement issue #${issue.number}`]);
  await exec.exec("git", ["push", "origin", branch]);

  // Collect metrics
  const diffStat = await execWithOutput("git", ["diff", "HEAD~1", "HEAD", "--numstat"]);
  let linesAdded = 0;
  let linesRemoved = 0;
  for (const line of diffStat.split("\n").filter(Boolean)) {
    const [added, removed] = line.split("\t");
    linesAdded += parseInt(added!) || 0;
    linesRemoved += parseInt(removed!) || 0;
  }
  const durationMs = Date.now() - startMs;

  // Resolve base branch
  let baseBranch = core.getState("base_branch");
  if (!baseBranch) {
    try {
      baseBranch = await execWithOutput("gh", [
        "repo",
        "view",
        "--json",
        "defaultBranchRef",
        "-q",
        ".defaultBranchRef.name",
      ]);
    } catch (err) {
      core.warning(`Could not resolve default branch, falling back to "main": ${err}`);
      baseBranch = "main";
    }
  }

  // Create PR
  const prTitle = prPrefix.charAt(0).toUpperCase() + prPrefix.slice(1);
  const prBody = `Closes #${issue.number}\n\n---\nGenerated by [${prPrefix}](${runUrl})`;
  let prUrl = "";
  try {
    prUrl = await execWithOutput("gh", [
      "pr",
      "create",
      "--title",
      `${prTitle}: ${issue.title}`,
      "--body",
      prBody,
      "--base",
      baseBranch,
      "--head",
      branch,
    ]);
  } catch (err) {
    core.warning(`PR creation failed: ${err}. May already exist.`);
  }

  const prNumberMatch = prUrl.match(/\/pull\/(\d+)/);
  const pullRequestNumber = prNumberMatch ? parseInt(prNumberMatch[1]!) : undefined;

  // Post implement.completed event via API
  const agentsToken = core.getInput("agents_token");
  const apiUrl = core.getInput("api_url");
  if (agentsToken) {
    const sdk = createApiClient(agentsToken, apiUrl);
    try {
      const customMetrics = readCustomMetrics(process.env.IMPLEMENT_METRICS ?? "");
      const tags = uniqueTags([
        `gh:repo:${repository}`,
        `gh:issue:${issue.number}`,
        `gh:branch:${branch}`,
        ...(pullRequestNumber ? [`gh:pr:${pullRequestNumber}`] : []),
        ...metricTags({
          duration_ms: durationMs,
          lines_added: linesAdded,
          lines_removed: linesRemoved,
        }),
        ...(customMetrics.harness ? [`harness:${customMetrics.harness}`] : []),
        ...(customMetrics.model ? [`model:${customMetrics.model}`] : []),
        ...extraTags,
      ]);
      await sdk.postEvents({
        eventIngestInput: {
          repoFullName: repository,
          parentEventId: startEventId || null,
          origin: "action",
          type: "agents.implement.completed",
          tags,
          data: {
            branch,
            issueNumber: issue.number,
            pullRequestNumber: pullRequestNumber ?? null,
            linesAdded,
            linesRemoved,
            durationMs,
            prUrl,
            runUrl,
            metrics: customMetrics,
          },
        },
      });
    } catch (err) {
      core.warning(`Failed to post implement.completed event: ${err}`);
    }
  }

  // Write job summary
  const customMetrics = readCustomMetrics(process.env.IMPLEMENT_METRICS ?? "");
  const customRows = Object.entries(customMetrics) as [string, string][];

  await core.summary
    .addHeading(`${prTitle} Implementation`)
    .addTable([
      [
        { data: "Metric", header: true },
        { data: "Value", header: true },
      ],
      ["Prefix", `\`${prPrefix}\``],
      ["Branch", `\`${branch}\``],
      ["Lines added", linesAdded.toString()],
      ["Lines removed", linesRemoved.toString()],
      ["Duration", `${durationMs}ms`],
      ["PR", prUrl],
      ["Run", runUrl],
      ...customRows,
    ])
    .write();
}

run().catch(core.setFailed);
