// This file is auto-generated by @hey-api/openapi-ts

import {
  buildClientParams,
  type Client,
  type Options as Options2,
  type TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  DeleteAppByIdErrors,
  DeleteAppByIdResponses,
  DeleteTokenByIdErrors,
  DeleteTokenByIdResponses,
  EventIngestInput,
  GetAppByIdErrors,
  GetAppByIdResponses,
  GetAppErrors,
  GetAppResponses,
  GetModelsPricingByModelIdErrors,
  GetModelsPricingByModelIdResponses,
  GetModelsPricingErrors,
  GetModelsPricingResponses,
  GetProfileErrors,
  GetProfileResponses,
  GetTokenByIdErrors,
  GetTokenByIdResponses,
  GetTokenErrors,
  GetTokenResponses,
  PatchEventsByIdErrors,
  PatchEventsByIdResponses,
  PostAppErrors,
  PostAppResponses,
  PostBranchArtifactsByOwnerByRepoByBranchResponses,
  PostEventsByIdArtifactsErrors,
  PostEventsByIdArtifactsResponses,
  PostEventsErrors,
  PostEventsResponses,
  PostGithubDispatchErrors,
  PostGithubDispatchResponses,
  PostModelsCostErrors,
  PostModelsCostResponses,
  PostTokenErrors,
  PostTokenResponses,
  PutProfileErrors,
  PutProfileResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

class HeyApiClient {
  protected client: Client;

  constructor(args?: { client?: Client }) {
    this.client = args?.client ?? client;
  }
}

class HeyApiRegistry<T> {
  private readonly defaultKey = "default";

  private readonly instances: Map<string, T> = new Map();

  get(key?: string): T {
    const instance = this.instances.get(key ?? this.defaultKey);
    if (!instance) {
      throw new Error(
        `No SDK client found. Create one with "new DevAgentSdk()" to fix this error.`,
      );
    }
    return instance;
  }

  set(value: T, key?: string): void {
    this.instances.set(key ?? this.defaultKey, value);
  }
}

export class DevAgentSdk extends HeyApiClient {
  public static readonly __registry = new HeyApiRegistry<DevAgentSdk>();

  constructor(args?: { client?: Client; key?: string }) {
    super(args);
    DevAgentSdk.__registry.set(this, args?.key);
  }

  /**
   * Get profile
   *
   * Get the current user's profile.
   */
  public getProfile<ThrowOnError extends boolean = false>(options?: Options<never, ThrowOnError>) {
    return (options?.client ?? this.client).get<
      GetProfileResponses,
      GetProfileErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/profile",
      ...options,
    });
  }

  /**
   * Update profile
   *
   * Update the current user's profile.
   */
  public putProfile<ThrowOnError extends boolean = false>(
    parameters: {
      name: string;
      email: string;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "body", key: "name" },
            { in: "body", key: "email" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).put<
      PutProfileResponses,
      PutProfileErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/profile",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * List apps
   *
   * List the current user's registered apps.
   */
  public getApp<ThrowOnError extends boolean = false>(options?: Options<never, ThrowOnError>) {
    return (options?.client ?? this.client).get<GetAppResponses, GetAppErrors, ThrowOnError>({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/app",
      ...options,
    });
  }

  /**
   * Create app
   *
   * Create an app.
   */
  public postApp<ThrowOnError extends boolean = false>(
    parameters: {
      name: string;
      redirectURI: string;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "body", key: "name" },
            { in: "body", key: "redirectURI" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).post<PostAppResponses, PostAppErrors, ThrowOnError>({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/app",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * Delete app
   *
   * Delete the app with the given ID.
   */
  public deleteAppById<ThrowOnError extends boolean = false>(
    parameters: {
      id: string;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams([parameters], [{ args: [{ in: "path", key: "id" }] }]);
    return (options?.client ?? this.client).delete<
      DeleteAppByIdResponses,
      DeleteAppByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/app/{id}",
      ...options,
      ...params,
    });
  }

  /**
   * Get app
   *
   * Get the app with the given ID.
   */
  public getAppById<ThrowOnError extends boolean = false>(
    parameters: {
      id: string;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams([parameters], [{ args: [{ in: "path", key: "id" }] }]);
    return (options?.client ?? this.client).get<
      GetAppByIdResponses,
      GetAppByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/app/{id}",
      ...options,
      ...params,
    });
  }

  /**
   * List tokens
   *
   * List the current user's personal access tokens.
   */
  public getToken<ThrowOnError extends boolean = false>(options?: Options<never, ThrowOnError>) {
    return (options?.client ?? this.client).get<GetTokenResponses, GetTokenErrors, ThrowOnError>({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/token",
      ...options,
    });
  }

  /**
   * Create token
   *
   * Create a personal access token.
   */
  public postToken<ThrowOnError extends boolean = false>(options?: Options<never, ThrowOnError>) {
    return (options?.client ?? this.client).post<PostTokenResponses, PostTokenErrors, ThrowOnError>(
      {
        security: [{ scheme: "bearer", type: "http" }],
        url: "/token",
        ...options,
      },
    );
  }

  /**
   * Delete token
   *
   * Delete the personal access token with the given ID.
   */
  public deleteTokenById<ThrowOnError extends boolean = false>(
    parameters: {
      id: string;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams([parameters], [{ args: [{ in: "path", key: "id" }] }]);
    return (options?.client ?? this.client).delete<
      DeleteTokenByIdResponses,
      DeleteTokenByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/token/{id}",
      ...options,
      ...params,
    });
  }

  /**
   * Get token
   *
   * Get the personal access token with the given ID.
   */
  public getTokenById<ThrowOnError extends boolean = false>(
    parameters: {
      id: string;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams([parameters], [{ args: [{ in: "path", key: "id" }] }]);
    return (options?.client ?? this.client).get<
      GetTokenByIdResponses,
      GetTokenByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/token/{id}",
      ...options,
      ...params,
    });
  }

  /**
   * Create event
   *
   * Record an event linked to a repository.
   */
  public postEvents<ThrowOnError extends boolean = false>(
    parameters: {
      eventIngestInput: EventIngestInput;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams(
      [parameters],
      [{ args: [{ key: "eventIngestInput", map: "body" }] }],
    );
    return (options?.client ?? this.client).post<
      PostEventsResponses,
      PostEventsErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/events",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * Update event
   *
   * Update data and/or tags on an existing event.
   */
  public patchEventsById<ThrowOnError extends boolean = false>(
    parameters: {
      id: string;
      data?: {
        [key: string]: unknown;
      };
      tags?: Array<string>;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "path", key: "id" },
            { in: "body", key: "data" },
            { in: "body", key: "tags" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).patch<
      PatchEventsByIdResponses,
      PatchEventsByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/events/{id}",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * Upload artifact
   *
   * Upload a file artifact associated with an event.
   */
  public postEventsByIdArtifacts<ThrowOnError extends boolean = false>(
    parameters: {
      id: string;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams([parameters], [{ args: [{ in: "path", key: "id" }] }]);
    return (options?.client ?? this.client).post<
      PostEventsByIdArtifactsResponses,
      PostEventsByIdArtifactsErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/events/{id}/artifacts",
      ...options,
      ...params,
    });
  }

  /**
   * Dispatch agent workflow
   *
   * Trigger an agent workflow via GitHub Actions workflow_dispatch. Accepts either a direct prompt or an issue number (which auto-fetches the issue to build the prompt).
   */
  public postGithubDispatch<ThrowOnError extends boolean = false>(
    parameters: {
      owner: string;
      repo: string;
      agent: "claude" | "opencode" | "codex";
      prompt?: string;
      issue_number?: number;
      tags?: Array<string>;
      model?: string;
      ref?: string;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "body", key: "owner" },
            { in: "body", key: "repo" },
            { in: "body", key: "agent" },
            { in: "body", key: "prompt" },
            { in: "body", key: "issue_number" },
            { in: "body", key: "tags" },
            { in: "body", key: "model" },
            { in: "body", key: "ref" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).post<
      PostGithubDispatchResponses,
      PostGithubDispatchErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/github/dispatch",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * List all model pricing
   *
   * Returns pricing data for all models. Costs are in dollars per 1M tokens.
   */
  public getModelsPricing<ThrowOnError extends boolean = false>(
    options?: Options<never, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).get<
      GetModelsPricingResponses,
      GetModelsPricingErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/models/pricing",
      ...options,
    });
  }

  /**
   * Get pricing for a model
   *
   * Looks up pricing for a model ID using exact match, then longest-prefix-match. Costs are in dollars per 1M tokens.
   */
  public getModelsPricingByModelId<ThrowOnError extends boolean = false>(
    parameters: {
      modelId: string;
      provider?: string;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "path", key: "modelId" },
            { in: "query", key: "provider" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).get<
      GetModelsPricingByModelIdResponses,
      GetModelsPricingByModelIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/models/pricing/{modelId}",
      ...options,
      ...params,
    });
  }

  /**
   * Calculate cost for model usage
   *
   * Given a model ID and token counts, resolves pricing via longest-prefix-match and returns the calculated cost in USD.
   */
  public postModelsCost<ThrowOnError extends boolean = false>(
    parameters: {
      model: string;
      provider?: string;
      tokens: {
        /**
         * Input tokens
         */
        input: number;
        /**
         * Output tokens
         */
        output: number;
        /**
         * Cache read tokens
         */
        cacheRead?: number;
        /**
         * Cache write tokens
         */
        cacheWrite?: number;
        /**
         * Reasoning tokens
         */
        reasoning?: number;
      };
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "body", key: "model" },
            { in: "body", key: "provider" },
            { in: "body", key: "tokens" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).post<
      PostModelsCostResponses,
      PostModelsCostErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/models/cost",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  public postBranchArtifactsByOwnerByRepoByBranch<ThrowOnError extends boolean = false>(
    parameters: {
      owner: string;
      repo: string;
      branch: string;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "path", key: "owner" },
            { in: "path", key: "repo" },
            { in: "path", key: "branch" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).post<
      PostBranchArtifactsByOwnerByRepoByBranchResponses,
      unknown,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/branch-artifacts/{owner}/{repo}/{branch}",
      ...options,
      ...params,
    });
  }
}
