// This file is auto-generated by @hey-api/openapi-ts

import {
  buildClientParams,
  type Client,
  type Options as Options2,
  type TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  DeleteAppByIdErrors,
  DeleteAppByIdResponses,
  DeleteTokenByIdErrors,
  DeleteTokenByIdResponses,
  GetAppByIdErrors,
  GetAppByIdResponses,
  GetAppErrors,
  GetAppResponses,
  GetProfileErrors,
  GetProfileResponses,
  GetTokenByIdErrors,
  GetTokenByIdResponses,
  GetTokenErrors,
  GetTokenResponses,
  PostAppErrors,
  PostAppResponses,
  PostGithubEventsByIdArtifactsErrors,
  PostGithubEventsByIdArtifactsResponses,
  PostGithubEventsErrors,
  PostGithubEventsResponses,
  PostTokenErrors,
  PostTokenResponses,
  PutProfileErrors,
  PutProfileResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

class HeyApiClient {
  protected client: Client;

  constructor(args?: { client?: Client }) {
    this.client = args?.client ?? client;
  }
}

class HeyApiRegistry<T> {
  private readonly defaultKey = "default";

  private readonly instances: Map<string, T> = new Map();

  get(key?: string): T {
    const instance = this.instances.get(key ?? this.defaultKey);
    if (!instance) {
      throw new Error(
        `No SDK client found. Create one with "new DevAgentSdk()" to fix this error.`,
      );
    }
    return instance;
  }

  set(value: T, key?: string): void {
    this.instances.set(key ?? this.defaultKey, value);
  }
}

export class DevAgentSdk extends HeyApiClient {
  public static readonly __registry = new HeyApiRegistry<DevAgentSdk>();

  constructor(args?: { client?: Client; key?: string }) {
    super(args);
    DevAgentSdk.__registry.set(this, args?.key);
  }

  /**
   * Get profile
   *
   * Get the current user's profile.
   */
  public getProfile<ThrowOnError extends boolean = false>(options?: Options<never, ThrowOnError>) {
    return (options?.client ?? this.client).get<
      GetProfileResponses,
      GetProfileErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/profile",
      ...options,
    });
  }

  /**
   * Update profile
   *
   * Update the current user's profile.
   */
  public putProfile<ThrowOnError extends boolean = false>(
    parameters: {
      name: string;
      email: string;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "body", key: "name" },
            { in: "body", key: "email" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).put<
      PutProfileResponses,
      PutProfileErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/profile",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * List apps
   *
   * List the current user's registered apps.
   */
  public getApp<ThrowOnError extends boolean = false>(options?: Options<never, ThrowOnError>) {
    return (options?.client ?? this.client).get<GetAppResponses, GetAppErrors, ThrowOnError>({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/app",
      ...options,
    });
  }

  /**
   * Create app
   *
   * Create an app.
   */
  public postApp<ThrowOnError extends boolean = false>(
    parameters: {
      name: string;
      redirectURI: string;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "body", key: "name" },
            { in: "body", key: "redirectURI" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).post<PostAppResponses, PostAppErrors, ThrowOnError>({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/app",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * Delete app
   *
   * Delete the app with the given ID.
   */
  public deleteAppById<ThrowOnError extends boolean = false>(
    parameters: {
      id: string;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams([parameters], [{ args: [{ in: "path", key: "id" }] }]);
    return (options?.client ?? this.client).delete<
      DeleteAppByIdResponses,
      DeleteAppByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/app/{id}",
      ...options,
      ...params,
    });
  }

  /**
   * Get app
   *
   * Get the app with the given ID.
   */
  public getAppById<ThrowOnError extends boolean = false>(
    parameters: {
      id: string;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams([parameters], [{ args: [{ in: "path", key: "id" }] }]);
    return (options?.client ?? this.client).get<
      GetAppByIdResponses,
      GetAppByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/app/{id}",
      ...options,
      ...params,
    });
  }

  /**
   * List tokens
   *
   * List the current user's personal access tokens.
   */
  public getToken<ThrowOnError extends boolean = false>(options?: Options<never, ThrowOnError>) {
    return (options?.client ?? this.client).get<GetTokenResponses, GetTokenErrors, ThrowOnError>({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/token",
      ...options,
    });
  }

  /**
   * Create token
   *
   * Create a personal access token.
   */
  public postToken<ThrowOnError extends boolean = false>(options?: Options<never, ThrowOnError>) {
    return (options?.client ?? this.client).post<PostTokenResponses, PostTokenErrors, ThrowOnError>(
      {
        security: [{ scheme: "bearer", type: "http" }],
        url: "/token",
        ...options,
      },
    );
  }

  /**
   * Delete token
   *
   * Delete the personal access token with the given ID.
   */
  public deleteTokenById<ThrowOnError extends boolean = false>(
    parameters: {
      id: string;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams([parameters], [{ args: [{ in: "path", key: "id" }] }]);
    return (options?.client ?? this.client).delete<
      DeleteTokenByIdResponses,
      DeleteTokenByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/token/{id}",
      ...options,
      ...params,
    });
  }

  /**
   * Get token
   *
   * Get the personal access token with the given ID.
   */
  public getTokenById<ThrowOnError extends boolean = false>(
    parameters: {
      id: string;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams([parameters], [{ args: [{ in: "path", key: "id" }] }]);
    return (options?.client ?? this.client).get<
      GetTokenByIdResponses,
      GetTokenByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/token/{id}",
      ...options,
      ...params,
    });
  }

  /**
   * Create event
   *
   * Record a GitHub or agent event linked to a repository and optionally an issue or pull request. Intended for use by `actions/implement` and other external sources.
   */
  public postGithubEvents<ThrowOnError extends boolean = false>(
    parameters: {
      repoFullName: string;
      parentEventId?: string | null;
      issueNumber?: number | null;
      pullRequestNumber?: number | null;
      source: "webhook" | "action" | "cli" | "console";
      type: string;
      payload?: {
        [key: string]: unknown;
      };
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "body", key: "repoFullName" },
            { in: "body", key: "parentEventId" },
            { in: "body", key: "issueNumber" },
            { in: "body", key: "pullRequestNumber" },
            { in: "body", key: "source" },
            { in: "body", key: "type" },
            { in: "body", key: "payload" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).post<
      PostGithubEventsResponses,
      PostGithubEventsErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/github/events",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * Upload artifact
   *
   * Upload a file artifact associated with a GitHub event.
   */
  public postGithubEventsByIdArtifacts<ThrowOnError extends boolean = false>(
    parameters: {
      id: string;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams([parameters], [{ args: [{ in: "path", key: "id" }] }]);
    return (options?.client ?? this.client).post<
      PostGithubEventsByIdArtifactsResponses,
      PostGithubEventsByIdArtifactsErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/github/events/{id}/artifacts",
      ...options,
      ...params,
    });
  }
}
