// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl:
    | "https://agents-dev.developing.company/api"
    | "https://agents.developing.company/api"
    | (string & {});
};

/**
 * A user.
 */
export type User = {
  /**
   * Unique object identifier.
   * The format and length of IDs may change over time.
   */
  id: string;
  /**
   * Name of the user.
   */
  name: string | null;
  /**
   * Email address of the user.
   */
  email: string | null;
  /**
   * GitHub username of the user.
   */
  username: string | null;
  /**
   * Avatar URL of the user.
   */
  avatarUrl: string | null;
};

/**
 * Updated user profile information.
 */
export type Profile = {
  user: User;
};

/**
 * Permission error
 */
export type ErrorResponse = {
  /**
   * The error type category
   */
  type: "validation" | "authentication" | "forbidden" | "not_found" | "rate_limit" | "internal";
  /**
   * Machine-readable error code identifier
   */
  code: string;
  /**
   * Human-readable error message
   */
  message: string;
  /**
   * The parameter that caused the error (if applicable)
   */
  param?: string;
  /**
   * Additional error context information
   */
  details?: unknown;
};

/**
 * App.
 */
export type App = {
  /**
   * Unique object identifier.
   * The format and length of IDs may change over time.
   */
  id: string;
  /**
   * Name of the app.
   */
  name: string;
  /**
   * Redirect URI of the app.
   */
  redirectURI: string;
  /**
   * OAuth 2.0 client secret of the app (obfuscated).
   */
  secret: string;
};

/**
 * Personal access token.
 */
export type Token = {
  /**
   * Unique object identifier.
   * The format and length of IDs may change over time.
   */
  id: string;
  /**
   * The created time for the token.
   */
  created: string;
  /**
   * Personal access token (obfuscated).
   */
  token: string;
};

/**
 * A recorded system or agent event.
 */
export type Event = {
  /**
   * Unique object identifier.
   * The format and length of IDs may change over time.
   */
  id: string;
  /**
   * ID of the parent event, if this event is part of a chain.
   */
  parentEventId: string | null;
  /**
   * Source entity type, e.g. 'repository'.
   */
  source: string | null;
  /**
   * ID of the source entity.
   */
  sourceId: string | null;
  /**
   * Event type, e.g. 'github.issues.opened'.
   */
  type: string;
  /**
   * What triggered this event.
   */
  origin: "api" | "webhook" | "action" | "console" | "cli" | "cron";
  /**
   * Searchable tags, e.g. 'gh:repo:owner/name', 'gh:issue:42'.
   */
  tags: Array<string>;
  /**
   * Arbitrary event data.
   */
  data: {
    [key: string]: unknown;
  };
  /**
   * ISO timestamp when the event was recorded.
   */
  timeCreated: string;
};

/**
 * Event payload submitted by external producers.
 */
export type EventIngestInput = (
  | {
      /**
       * Unique object identifier.
       * The format and length of IDs may change over time.
       */
      repositoryId: string;
    }
  | {
      /**
       * Full repository name in `owner/repo` format.
       */
      repoFullName: string;
    }
) & {
  /**
   * Parent event ID to group related events.
   */
  parentEventId?: string | null;
  /**
   * What triggered this event.
   */
  origin: "api" | "webhook" | "action" | "console" | "cli" | "cron";
  /**
   * Event type, e.g. 'github.issues.opened'.
   */
  type: string;
  /**
   * Searchable tags, e.g. 'gh:repo:owner/name', 'gh:issue:42'.
   */
  tags?: Array<string>;
  /**
   * Arbitrary event data.
   */
  data?: {
    [key: string]: unknown;
  };
};

/**
 * An artifact stored in R2 associated with an event.
 */
export type EventArtifact = {
  /**
   * R2 storage key for the artifact.
   */
  key: string;
  /**
   * Artifact filename.
   */
  name: string;
  /**
   * Artifact size in bytes.
   */
  size: number;
  /**
   * ISO timestamp when the artifact was uploaded.
   */
  uploaded: string;
};

export type GetProfileData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/profile";
};

export type GetProfileErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Too Many Requests
   */
  429: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetProfileError = GetProfileErrors[keyof GetProfileErrors];

export type GetProfileResponses = {
  /**
   * User profile information.
   */
  200: Profile;
};

export type GetProfileResponse = GetProfileResponses[keyof GetProfileResponses];

export type PutProfileData = {
  /**
   * The user's updated profile information.
   */
  body: {
    name: string;
    email: string;
  };
  path?: never;
  query?: never;
  url: "/profile";
};

export type PutProfileErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Too Many Requests
   */
  429: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type PutProfileError = PutProfileErrors[keyof PutProfileErrors];

export type PutProfileResponses = {
  /**
   * Updated user profile information.
   */
  200: Profile;
};

export type PutProfileResponse = PutProfileResponses[keyof PutProfileResponses];

export type GetAppData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/app";
};

export type GetAppErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Too Many Requests
   */
  429: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetAppError = GetAppErrors[keyof GetAppErrors];

export type GetAppResponses = {
  /**
   * List of apps.
   */
  200: Array<App>;
};

export type GetAppResponse = GetAppResponses[keyof GetAppResponses];

export type PostAppData = {
  /**
   * Basic app information.
   */
  body: {
    name: string;
    redirectURI: string;
  };
  path?: never;
  query?: never;
  url: "/app";
};

export type PostAppErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Too Many Requests
   */
  429: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type PostAppError = PostAppErrors[keyof PostAppErrors];

export type PostAppResponses = {
  /**
   * OAuth 2.0 client ID and secret.
   */
  200: {
    /**
     * OAuth 2.0 client ID.
     */
    id: string;
    /**
     * OAuth 2.0 client secret.
     */
    secret: string;
  };
};

export type PostAppResponse = PostAppResponses[keyof PostAppResponses];

export type DeleteAppByIdData = {
  body?: never;
  path: {
    /**
     * ID of the app to delete.
     */
    id: string;
  };
  query?: never;
  url: "/app/{id}";
};

export type DeleteAppByIdErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Too Many Requests
   */
  429: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type DeleteAppByIdError = DeleteAppByIdErrors[keyof DeleteAppByIdErrors];

export type DeleteAppByIdResponses = {
  /**
   * App was deleted successfully.
   */
  200: "ok";
};

export type DeleteAppByIdResponse = DeleteAppByIdResponses[keyof DeleteAppByIdResponses];

export type GetAppByIdData = {
  body?: never;
  path: {
    /**
     * ID of the app to get.
     */
    id: string;
  };
  query?: never;
  url: "/app/{id}";
};

export type GetAppByIdErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Too Many Requests
   */
  429: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetAppByIdError = GetAppByIdErrors[keyof GetAppByIdErrors];

export type GetAppByIdResponses = {
  /**
   * App.
   */
  200: App;
};

export type GetAppByIdResponse = GetAppByIdResponses[keyof GetAppByIdResponses];

export type GetTokenData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/token";
};

export type GetTokenErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Too Many Requests
   */
  429: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetTokenError = GetTokenErrors[keyof GetTokenErrors];

export type GetTokenResponses = {
  /**
   * List of personal access tokens.
   */
  200: Array<Token>;
};

export type GetTokenResponse = GetTokenResponses[keyof GetTokenResponses];

export type PostTokenData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/token";
};

export type PostTokenErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Too Many Requests
   */
  429: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type PostTokenError = PostTokenErrors[keyof PostTokenErrors];

export type PostTokenResponses = {
  /**
   * Personal access token ID and value.
   */
  200: {
    /**
     * Personal token ID.
     */
    id: string;
    /**
     * Personal access token. Include this in the Authorization header (`Bearer <token>`) when accessing the API.
     */
    token: string;
  };
};

export type PostTokenResponse = PostTokenResponses[keyof PostTokenResponses];

export type DeleteTokenByIdData = {
  body?: never;
  path: {
    /**
     * ID of the personal token to delete.
     */
    id: string;
  };
  query?: never;
  url: "/token/{id}";
};

export type DeleteTokenByIdErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Too Many Requests
   */
  429: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type DeleteTokenByIdError = DeleteTokenByIdErrors[keyof DeleteTokenByIdErrors];

export type DeleteTokenByIdResponses = {
  /**
   * Personal access token was deleted successfully.
   */
  200: "ok";
};

export type DeleteTokenByIdResponse = DeleteTokenByIdResponses[keyof DeleteTokenByIdResponses];

export type GetTokenByIdData = {
  body?: never;
  path: {
    /**
     * ID of the personal token to get.
     */
    id: string;
  };
  query?: never;
  url: "/token/{id}";
};

export type GetTokenByIdErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Too Many Requests
   */
  429: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetTokenByIdError = GetTokenByIdErrors[keyof GetTokenByIdErrors];

export type GetTokenByIdResponses = {
  /**
   * Personal access token.
   */
  200: Token;
};

export type GetTokenByIdResponse = GetTokenByIdResponses[keyof GetTokenByIdResponses];

export type PostEventsData = {
  body: EventIngestInput;
  path?: never;
  query?: never;
  url: "/events";
};

export type PostEventsErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Too Many Requests
   */
  429: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type PostEventsError = PostEventsErrors[keyof PostEventsErrors];

export type PostEventsResponses = {
  /**
   * The created event.
   */
  200: Event;
};

export type PostEventsResponse = PostEventsResponses[keyof PostEventsResponses];

export type PostEventsByIdArtifactsData = {
  body?: never;
  path: {
    /**
     * Unique object identifier.
     * The format and length of IDs may change over time.
     */
    id: string;
  };
  query?: never;
  url: "/events/{id}/artifacts";
};

export type PostEventsByIdArtifactsErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Too Many Requests
   */
  429: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type PostEventsByIdArtifactsError =
  PostEventsByIdArtifactsErrors[keyof PostEventsByIdArtifactsErrors];

export type PostEventsByIdArtifactsResponses = {
  /**
   * The uploaded artifact metadata.
   */
  200: EventArtifact;
};

export type PostEventsByIdArtifactsResponse =
  PostEventsByIdArtifactsResponses[keyof PostEventsByIdArtifactsResponses];

export type PostGithubDispatchData = {
  body: {
    /**
     * Repository owner
     */
    owner: string;
    /**
     * Repository name
     */
    repo: string;
    /**
     * Agent to dispatch
     */
    agent: "claude" | "opencode" | "codex";
    /**
     * Task/instructions for the agent. Required if issue_number is not provided.
     */
    prompt?: string;
    /**
     * Issue number to implement. Auto-fetches title/body to build prompt and adds gh:issue tag.
     */
    issue_number?: number;
    /**
     * Additional tags for event linking (e.g. gh:issue:42)
     */
    tags?: Array<string>;
    /**
     * Model override
     */
    model?: string;
    /**
     * Git ref to dispatch on
     */
    ref?: string;
  };
  path?: never;
  query?: never;
  url: "/github/dispatch";
};

export type PostGithubDispatchErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type PostGithubDispatchError = PostGithubDispatchErrors[keyof PostGithubDispatchErrors];

export type PostGithubDispatchResponses = {
  /**
   * Workflow dispatched successfully.
   */
  200: {
    ok: boolean;
  };
};

export type PostGithubDispatchResponse =
  PostGithubDispatchResponses[keyof PostGithubDispatchResponses];

export type GetModelsPricingData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/models/pricing";
};

export type GetModelsPricingErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Too Many Requests
   */
  429: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetModelsPricingError = GetModelsPricingErrors[keyof GetModelsPricingErrors];

export type GetModelsPricingResponses = {
  /**
   * All model pricing
   */
  200: {
    models: {
      [key: string]: {
        /**
         * Resolved model ID
         */
        model: string;
        /**
         * Provider ID
         */
        provider: string;
        /**
         * Model pricing in USD per 1M tokens
         */
        cost: {
          /**
           * Input cost per 1M tokens (USD)
           */
          input?: number;
          /**
           * Output cost per 1M tokens (USD)
           */
          output?: number;
          /**
           * Cache read cost per 1M tokens (USD)
           */
          cache_read?: number;
          /**
           * Cache write cost per 1M tokens (USD)
           */
          cache_write?: number;
          /**
           * Reasoning token cost per 1M tokens (USD)
           */
          reasoning?: number;
          /**
           * Audio input cost per 1M tokens (USD)
           */
          input_audio?: number;
          /**
           * Audio output cost per 1M tokens (USD)
           */
          output_audio?: number;
          /**
           * Tiered pricing for contexts over 200k tokens
           */
          context_over_200k?: {
            input?: number;
            output?: number;
          };
        };
      };
    };
  };
};

export type GetModelsPricingResponse = GetModelsPricingResponses[keyof GetModelsPricingResponses];

export type GetModelsPricingByModelIdData = {
  body?: never;
  path: {
    /**
     * Model ID to look up (supports longest-prefix-match)
     */
    modelId: string;
  };
  query?: never;
  url: "/models/pricing/{modelId}";
};

export type GetModelsPricingByModelIdErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Too Many Requests
   */
  429: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetModelsPricingByModelIdError =
  GetModelsPricingByModelIdErrors[keyof GetModelsPricingByModelIdErrors];

export type GetModelsPricingByModelIdResponses = {
  /**
   * Model pricing (null if not found)
   */
  200: {
    pricing: {
      /**
       * Resolved model ID
       */
      model: string;
      /**
       * Provider ID
       */
      provider: string;
      /**
       * Model pricing in USD per 1M tokens
       */
      cost: {
        /**
         * Input cost per 1M tokens (USD)
         */
        input?: number;
        /**
         * Output cost per 1M tokens (USD)
         */
        output?: number;
        /**
         * Cache read cost per 1M tokens (USD)
         */
        cache_read?: number;
        /**
         * Cache write cost per 1M tokens (USD)
         */
        cache_write?: number;
        /**
         * Reasoning token cost per 1M tokens (USD)
         */
        reasoning?: number;
        /**
         * Audio input cost per 1M tokens (USD)
         */
        input_audio?: number;
        /**
         * Audio output cost per 1M tokens (USD)
         */
        output_audio?: number;
        /**
         * Tiered pricing for contexts over 200k tokens
         */
        context_over_200k?: {
          input?: number;
          output?: number;
        };
      };
    } | null;
  };
};

export type GetModelsPricingByModelIdResponse =
  GetModelsPricingByModelIdResponses[keyof GetModelsPricingByModelIdResponses];

export type PostModelsCostData = {
  body: {
    /**
     * Resolved model ID
     */
    model: string;
    /**
     * Token counts from model usage
     */
    tokens: {
      /**
       * Input tokens
       */
      input: number;
      /**
       * Output tokens
       */
      output: number;
      /**
       * Cache read tokens
       */
      cacheRead?: number;
      /**
       * Cache write tokens
       */
      cacheWrite?: number;
      /**
       * Reasoning tokens
       */
      reasoning?: number;
    };
  };
  path?: never;
  query?: never;
  url: "/models/cost";
};

export type PostModelsCostErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Too Many Requests
   */
  429: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type PostModelsCostError = PostModelsCostErrors[keyof PostModelsCostErrors];

export type PostModelsCostResponses = {
  /**
   * Calculated cost
   */
  200: {
    pricing: {
      /**
       * Resolved model ID
       */
      model: string;
      /**
       * Provider ID
       */
      provider: string;
      /**
       * Model pricing in USD per 1M tokens
       */
      cost: {
        /**
         * Input cost per 1M tokens (USD)
         */
        input?: number;
        /**
         * Output cost per 1M tokens (USD)
         */
        output?: number;
        /**
         * Cache read cost per 1M tokens (USD)
         */
        cache_read?: number;
        /**
         * Cache write cost per 1M tokens (USD)
         */
        cache_write?: number;
        /**
         * Reasoning token cost per 1M tokens (USD)
         */
        reasoning?: number;
        /**
         * Audio input cost per 1M tokens (USD)
         */
        input_audio?: number;
        /**
         * Audio output cost per 1M tokens (USD)
         */
        output_audio?: number;
        /**
         * Tiered pricing for contexts over 200k tokens
         */
        context_over_200k?: {
          input?: number;
          output?: number;
        };
      };
    } | null;
    /**
     * Total cost in USD
     */
    cost_usd: number | null;
  };
};

export type PostModelsCostResponse = PostModelsCostResponses[keyof PostModelsCostResponses];
