import { join } from "node:path";

const commandsDir = join(import.meta.dir, "src/commands");
const glob = new Bun.Glob("*.ts");

// Discover command files and generate a static index
const files: string[] = [];
for await (const file of glob.scan(commandsDir)) {
  if (file === "index.ts") continue;
  files.push(file.replace(/\.ts$/, ""));
}
files.sort();

const lines = [
  "// Auto-generated by build.ts — do not edit manually",
  ...files.map((f, i) => `import cmd${i} from "./${f}";`),
  "",
  `export const commands = [${files.map((_, i) => `cmd${i}`).join(", ")}];`,
  "",
];

await Bun.write(join(commandsDir, "index.ts"), lines.join("\n"));
console.log(`Generated commands/index.ts with: ${files.join(", ")}`);

// Compile — args: target, outfile (e.g.: bun build.ts bun-darwin-arm64 dist/dev-agents-macos)
const target = Bun.argv[2] ?? "bun";
const outfile = Bun.argv[3] ?? "dist/dev-agents";
await Bun.$`bun build ./src/cli.ts --compile --target=${target} --outfile=${outfile}`;
console.log(`Built ${outfile}`);
