// This file is auto-generated by @hey-api/openapi-ts

import {
  buildClientParams,
  type Client,
  type Options as Options2,
  type TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  CreateSandbox,
  CreateSandboxErrors,
  CreateSandboxResponses,
  EndSandboxErrors,
  EndSandboxResponses,
  GetSandboxErrors,
  GetSandboxResponses,
  HealthzErrors,
  HealthzResponses,
  ListSandboxesErrors,
  ListSandboxesResponses,
  OpenPreviewErrors,
  OpenPreviewResponses,
  OpenTerminalErrors,
  OpenTerminalResponses,
  PreviewBody,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

class HeyApiClient {
  protected client: Client;

  constructor(args?: { client?: Client }) {
    this.client = args?.client ?? client;
  }
}

class HeyApiRegistry<T> {
  private readonly defaultKey = "default";

  private readonly instances: Map<string, T> = new Map();

  get(key?: string): T {
    const instance = this.instances.get(key ?? this.defaultKey);
    if (!instance) {
      throw new Error(
        `No SDK client found. Create one with "new SandboxdSdk()" to fix this error.`,
      );
    }
    return instance;
  }

  set(value: T, key?: string): void {
    this.instances.set(key ?? this.defaultKey, value);
  }
}

export class SandboxdSdk extends HeyApiClient {
  public static readonly __registry = new HeyApiRegistry<SandboxdSdk>();

  constructor(args?: { client?: Client; key?: string }) {
    super(args);
    SandboxdSdk.__registry.set(this, args?.key);
  }

  /**
   * Liveness
   */
  public healthz<ThrowOnError extends boolean = false>(options?: Options<never, ThrowOnError>) {
    return (options?.client ?? this.client).get<HealthzResponses, HealthzErrors, ThrowOnError>({
      url: "/healthz",
      ...options,
    });
  }

  /**
   * List sandboxes
   *
   * This owner's sandboxes, newest first. There is no unscoped listing: the owner header is required on every route here, so no call can widen to the whole fleet by omitting something.
   */
  public listSandboxes<ThrowOnError extends boolean = false>(
    parameters: {
      "X-Sandboxd-Owner": string;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams(
      [parameters],
      [{ args: [{ in: "headers", key: "X-Sandboxd-Owner" }] }],
    );
    return (options?.client ?? this.client).get<
      ListSandboxesResponses,
      ListSandboxesErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/sandboxes",
      ...options,
      ...params,
    });
  }

  /**
   * Create a sandbox
   *
   * Presets are resolved before this call, by the client: the body names an image, a command, env and the host tags it needs. Answers 422 when no approved host can ever carry the required tags — a requirement the fleet is merely too full for queues instead, and the sandbox comes back `queued` with a `queue_position`.
   */
  public createSandbox<ThrowOnError extends boolean = false>(
    parameters: {
      "X-Sandboxd-Owner": string;
      createSandbox: CreateSandbox;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "headers", key: "X-Sandboxd-Owner" },
            { key: "createSandbox", map: "body" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).post<
      CreateSandboxResponses,
      CreateSandboxErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/sandboxes",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * End a sandbox
   *
   * Returns the sandbox as it stands: already `ended` when it was queued or its host is gone, still `running` while its host is being told.
   */
  public endSandbox<ThrowOnError extends boolean = false>(
    parameters: {
      "X-Sandboxd-Owner": string;
      id: string;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "headers", key: "X-Sandboxd-Owner" },
            { in: "path", key: "id" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).delete<
      EndSandboxResponses,
      EndSandboxErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/sandboxes/{id}",
      ...options,
      ...params,
    });
  }

  /**
   * Get a sandbox
   *
   * 404 both when there is no such sandbox and when it belongs to another owner: the two are deliberately indistinguishable.
   */
  public getSandbox<ThrowOnError extends boolean = false>(
    parameters: {
      "X-Sandboxd-Owner": string;
      id: string;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "headers", key: "X-Sandboxd-Owner" },
            { in: "path", key: "id" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).get<
      GetSandboxResponses,
      GetSandboxErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/sandboxes/{id}",
      ...options,
      ...params,
    });
  }

  /**
   * Open a terminal
   *
   * Returns the URL to attach to, good for 60 s and scoped to this one sandbox. Hand it to a browser. 409 while the sandbox is not `running` — there is no PTY yet.
   */
  public openTerminal<ThrowOnError extends boolean = false>(
    parameters: {
      "X-Sandboxd-Owner": string;
      id: string;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "headers", key: "X-Sandboxd-Owner" },
            { in: "path", key: "id" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).post<
      OpenTerminalResponses,
      OpenTerminalErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/sandboxes/{id}/terminal",
      ...options,
      ...params,
    });
  }

  /**
   * Open a preview
   *
   * Returns the URL a port inside the sandbox is reachable at, good for 10 min. Hand it to a browser: the first request there trades the token in the URL for a subdomain-scoped cookie and redirects to a clean address, so the token does not stay in the address bar. The preview itself is served from `<port>-<sid>.<preview domain>`, not from this API.
   */
  public openPreview<ThrowOnError extends boolean = false>(
    parameters: {
      "X-Sandboxd-Owner": string;
      id: string;
      previewBody: PreviewBody;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "headers", key: "X-Sandboxd-Owner" },
            { in: "path", key: "id" },
            { key: "previewBody", map: "body" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).post<
      OpenPreviewResponses,
      OpenPreviewErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/sandboxes/{id}/preview",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }
}
